resolver: lts-17.4

allow-newer: true

packages:
- smash
- smash-servant-types

flags:
  # Bundle VRF crypto in libsodium and do not rely on an external fork to have it.
  # This still requires the host system to have the 'standard' libsodium installed.
  cardano-crypto-praos:
    external-libsodium-vrf: false

ghc-options:
  smash:                    -Wall -Werror -fno-warn-redundant-constraints
  #smash-servant-types:      -Wall -Werror -fno-warn-redundant-constraints

# Generate files required by Weeder.
# See https://github.com/ndmitchell/weeder/issues/53
ghc-options:
  "$locals": -fwrite-ide-info -ddump-to-file -ddump-hi

extra-deps:
  - Cabal-3.4.0.0
  - async-timer-0.2.0.0
  - parsec-3.1.14.0
  - base16-0.1.2.1
  - base16-bytestring-1.0.1.0
  - base58-bytestring-0.1.0
  - base64-0.4.2
  - bech32-1.1.0
  - bech32-th-1.0.2
  - binary-0.8.7.0
  - bimap-0.4.0
  - canonical-json-0.6.0.0
  - cborg-0.2.4.0
  - clock-0.8
  - config-ini-0.2.4.0
  - connection-0.3.1
  - containers-0.5.11.0
  - data-clist-0.1.2.2
  - dns-3.0.4
  - generic-monoid-0.1.0.0
  - generics-sop-0.5.1.0
  - ghc-byteorder-4.11.0.0.10
  - gray-code-0.3.1
  - hedgehog-1.0.5
  - hedgehog-corpus-0.2.0
  - hedgehog-quickcheck-0.1.1
  - hspec-2.7.0
  - hspec-core-2.7.0
  - hspec-discover-2.7.0
  - io-streams-1.5.1.0
  - io-streams-haproxy-1.0.1.0
  - katip-0.8.4.0
  - libsystemd-journal-1.4.4
  - micro-recursion-schemes-5.0.2.2
  - moo-1.2
  - network-3.1.2.1
  - partial-order-0.2.0.0
  - prettyprinter-1.7.0
  - primitive-0.7.1.0
  - protolude-0.3.0
  - quiet-0.2
  - semialign-1.1.0.1
  - snap-core-1.0.4.1
  - snap-server-1.1.1.1
  - sop-core-0.5.0.1
  - statistics-linreg-0.3
  - streaming-binary-0.2.2.0
  - streaming-bytestring-0.2.0
  - systemd-2.3.0
  - tasty-hedgehog-1.0.0.2
  - text-1.2.4.0
  - text-ansi-0.1.0
  - text-conversions-0.3.1
  - text-zipper-0.10.1
  - th-lift-instances-0.1.14
  - these-1.1.1.1
  - time-units-1.0.0
  - transformers-except-0.1.1
  - unordered-containers-0.2.12.0
  - Unique-0.4.7.6
  - word-wrap-0.4.1
  - websockets-0.12.6.1
  - Win32-2.6.2.0
  - nothunks-0.1.2

  # db-sync dependency
  - git: https://github.com/input-output-hk/cardano-db-sync
    commit: 07ee3b0aa3f2991eda0be6c96ec1d6d17e81f732
    subdirs:
      - cardano-sync
      - cardano-db
      - cardano-db-sync

  - git: https://github.com/input-output-hk/cardano-base
    commit: cb0f19c85e5bb5299839ad4ed66af6fa61322cc4
    subdirs:
    - binary
    - binary/test
    - cardano-crypto-class
    - cardano-crypto-tests
    - cardano-crypto-praos
    - slotting

  - git: https://github.com/input-output-hk/cardano-crypto
    commit: 07397f0e50da97eaa0575d93bee7ac4b2b2576ec

  - git: https://github.com/input-output-hk/cardano-ledger-specs
    commit: 6aa1cd0a64a464371b94d4ac182e7e2cddc83a36
    subdirs:
    - alonzo/impl
    - byron/crypto
    - byron/crypto/test
    - byron/chain/executable-spec
    - byron/ledger/executable-spec
    - byron/ledger/impl
    - byron/ledger/impl/test
    - semantics/executable-spec
    - semantics/small-steps-test
    - shelley/chain-and-ledger/dependencies/non-integer
    - shelley/chain-and-ledger/executable-spec
    - shelley/chain-and-ledger/shelley-spec-ledger-test
    - shelley-ma/impl
    - shelley-ma/shelley-ma-test

  - git: https://github.com/input-output-hk/cardano-node
    commit: 4c59442958072657812c6c0bb8e0b4ab85ce1ba2
    subdirs:
    - cardano-api
    - cardano-api/test
    - cardano-cli
    - cardano-config
    - cardano-node
    - cardano-node-chairman
    - hedgehog-extras

  - git: https://github.com/input-output-hk/cardano-prelude
    commit: fd773f7a58412131512b9f694ab95653ac430852
    subdirs:
    - cardano-prelude
    - cardano-prelude-test

  - git: https://github.com/input-output-hk/cardano-sl-x509
    commit: 43a036c5bbe68ca2e9cbe611eab7982e2348fe49

  - git: https://github.com/input-output-hk/goblins
    commit: cde90a2b27f79187ca8310b6549331e59595e7ba

  - git: https://github.com/input-output-hk/iohk-monitoring-framework
    commit: 808724ff8a19a33d0ed06f9ef59fbd900b08553c
    subdirs:
    - contra-tracer
    - iohk-monitoring
    - plugins/backend-aggregation
    - plugins/backend-ekg
    - plugins/backend-monitoring
    - plugins/backend-trace-forwarder
    - plugins/scribe-systemd
    - tracer-transformers

  - git: https://github.com/input-output-hk/ouroboros-network
    commit: 877ce057ff6fb086474c8eaad53f2b7f0e0fce6b
    subdirs:
    - io-sim
    - io-sim-classes
    - monoidal-synchronisation
    - network-mux
    - ouroboros-consensus
    - ouroboros-consensus-byron
    - ouroboros-consensus-cardano
    - ouroboros-consensus-shelley
    - ouroboros-network
    - ouroboros-network-framework
    - typed-protocols
    - typed-protocols-examples
    # Extra packages not used by cardano-node
    - cardano-client
    - ntp-client
    - ouroboros-consensus-mock

  - git : https://github.com/input-output-hk/Win32-network
    commit: 3825d3abf75f83f406c1f7161883c438dac7277d

  - git: https://github.com/input-output-hk/plutus
    commit: edc6d4672c41de4485444122ff843bc86ff421a0
    subdirs:
    - plutus-core
    - plutus-ledger-api
    - plutus-tx
    - prettyprinter-configurable

  - git: https://github.com/snoyberg/http-client.git
    commit: 1a75bdfca014723dd5d40760fad854b3f0f37156
    subdirs:
    - http-client

  # Plutus deps
  - Stream-0.4.7.2
  - composition-prelude-3.0.0.2
  - dependent-map-0.4.0.0
  - dependent-sum-0.6.2.0
  - dependent-sum-template-0.1.0.3
  - lazy-search-0.1.2.1
  - monoidal-containers-0.6.0.1
  - size-based-0.1.2.0
  - witherable-0.4.1
  - constraints-extras-0.3.0.2
  - indexed-traversable-instances-0.1
  - lazysmallcheck-0.6

  # Additional deps
  - persistent-2.11.0.1
  - persistent-postgresql-2.11.0.0
  - persistent-template-2.9.1.0

  - esqueleto-3.4.0.1

  # Compiler error 'System.Metrics.Prometheus.Http.Scrape (serveMetricsT)'
  - prometheus-2.2.2

  # Testing
  - quickcheck-state-machine-0.7.0
  - markov-chain-usage-model-0.0.0

nix:
  shell-file: nix/stack-shell.nix
